[package]
name = "system-configuration-proc"
version = "0.6.1"
repository = "https://github.com/mullvad/system-configuration-rs"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.64.0"
publish = false

[dependencies]
syn = { version = "2.0", features = ["full"] }