/* automatically generated by rust-bindgen 0.70.1 */

// Generated using:
// bindgen 0.70.1
// macOS SDK 14.5.

#[repr(C)]
pub struct __SCPreferences(c_void);

pub type SCPreferencesRef = *const __SCPreferences;
extern "C" {
    pub fn SCPreferencesPathCreateUniqueChild(
        prefs: SCPreferencesRef,
        prefix: CFStringRef,
    ) -> CFStringRef;

    pub fn SCPreferencesPathGetValue(prefs: SCPreferencesRef, path: CFStringRef)
        -> CFDictionaryRef;

    pub fn SCPreferencesPathGetLink(prefs: SCPreferencesRef, path: CFStringRef) -> CFStringRef;

    pub fn SCPreferencesPathSetValue(
        prefs: SCPreferencesRef,
        path: CFStringRef,
        value: CFDictionaryRef,
    ) -> Boolean;

    pub fn SCPreferencesPathSetLink(
        prefs: SCPreferencesRef,
        path: CFStringRef,
        link: CFStringRef,
    ) -> Boolean;

    pub fn SCPreferencesPathRemoveValue(prefs: SCPreferencesRef, path: CFStringRef) -> Boolean;
}
