use num_enum::{IntoPrimitive, TryFromPrimitive};
use strum::{AsRefStr, IntoStaticStr};
use sys::system_configuration::{
    kSCStatusAccessError, kSCStatusConnectionIgnore, kSCStatusConnectionNoService, kSCStatusFailed,
    kSCStatusInvalidArgument, kSCStatusKeyExists, kSCStatusLocked, kSCStatusMaxLink, kSCStatusNeedLock,
    kSCStatusNoConfigFile, kSCStatusNoKey, kSCStatusNoLink, kSCStatusNoPrefsSession, kSCStatusNoStoreServer,
    kSCStatusNoStoreSession, kSCStatusNotifierActive, kSCStatusOK, kSCStatusPrefsBusy, kSCStatusReachabilityUnknown,
    kSCStatusStale
};

/// A ***known type*** of status or error code generated by the most recent System Configuration
/// function call.
///
/// See [Apple's Documentation] for details.
///
/// [Apple Documentation]: https://developer.apple.com/documentation/systemconfiguration/1518026-status-and-error-codes?language=objc
#[derive(
    Debug, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Hash,
    IntoPrimitive, TryFromPrimitive,
    IntoStaticStr, AsRefStr,
)]
#[repr(u32)]
pub enum SCStatusType {
    /// The call was successful.
    OK = kSCStatusOK,
    /// A nonspecific failure occurred.
    Failed = kSCStatusFailed,
    /// An invalid argument was specified.
    InvalidArgument = kSCStatusInvalidArgument,
    /// Permission is denied; you must be root to obtain a lock. As a result, the function could not
    /// create or access preferences.
    AccessError = kSCStatusAccessError,
    /// No such key.
    NoKey = kSCStatusNoKey,
    /// Data associated with key already defined.
    KeyExists = kSCStatusKeyExists,
    /// A lock is already held.
    Locked = kSCStatusLocked,
    /// A lock is required for this operation.
    NeedLock = kSCStatusNeedLock,
    /// The configuration daemon session is not active.
    NoStoreSession = kSCStatusNoStoreSession,
    /// The configuration daemon is not available or no longer available.
    NoStoreServer = kSCStatusNoStoreServer,
    /// Notifier is currently active.
    NotifierActive = kSCStatusNotifierActive,
    /// The preferences session is not active.
    NoPrefsSession = kSCStatusNoPrefsSession,
    /// A preferences update is currently in progress.
    PrefsBusy = kSCStatusPrefsBusy,
    /// The configuration file cannot be found.
    NoConfigFile = kSCStatusNoConfigFile,
    /// No such link exists.
    NoLink = kSCStatusNoLink,
    /// A write was attempted on a stale version of the object.
    Stale = kSCStatusStale,
    /// The maximum link count is exceeded.
    MaxLink = kSCStatusMaxLink,
    /// Network reachability cannot be determined.
    ReachabilityUnknown = kSCStatusReachabilityUnknown,
    /// Network service for the connection is not available.
    ConnectionNoService = kSCStatusConnectionNoService,
    /// Network connection information is not available at this time.
    ConnectionIgnore = kSCStatusConnectionIgnore,
}

// implementations for status type
mod status_type_impls {
    use std::fmt;
    use sys::core_foundation_sys::base::OSStatus;
    use crate::status_temp::SCStatusType;

    // impl fmt::Debug for SCStatusType {
    //     #[cold]
    //     fn fmt(&self, fmt: &mut fmt::Formatter<'_>) -> fmt::Result {
    //         // fmt.debug
    //
    //
    //         // let mut builder = fmt.debug_struct("Error");
    //         // builder.field("code", &self.0)
    //         //     .field("message", &self.message())
    //         //     .finish()
    //     }
    // }

    // impl SCStatusType {
    //     pub fn message()
    // }

    impl From<SCStatusType> for OSStatus {
        fn from(value: SCStatusType) -> Self {
            Into::<u8>::into(value).into()
        }
    }
}

















